Repository VG-software-foundations/CBox-BE, pull requests merged in 2024-09, with the labels that each got.

#17 Initial
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  compose.yaml
  migrations/master.xml
  mvnw
  mvnw.cmd
  pom.xml
  scripts/config/grafana/Dockerfile
  scripts/config/grafana/provisioning/dashboards/all.yaml
  scripts/config/grafana/provisioning/dashboards/jvm-micrometer_rev9.json
  scripts/config/grafana/provisioning/dashboards/micrometer-spring-throughput_rev2.json
  scripts/config/grafana/provisioning/datasources/all.yaml
  scripts/config/prometheus.yml
  src/main/java/com/example/cbox/CBoxApplication.java
  src/main/resources/application.yml
  src/test/java/com/example/cbox/CBoxApplicationTests.java
  src/test/java/com/example/cbox/TestCBoxApplication.java
  src/test/java/com/example/cbox/TestcontainersConfiguration.java
Labels: enhancement, CI/CD

#18 CI
  .github/workflows/cbox.yml
Labels: enhancement, CI/CD

#23 Added db.changelog and mock.json file
  api/mock.json
  migrations/db.changelog-1.0.sql
  migrations/master.xml
Labels: DB

#24 Added ERD for our database
  docs/Diagram.jpeg
  docs/ERD.pgerd
Labels: DB

#26 User CRUD Ops
  migrations/db.changelog-1.0.sql
  migrations/db.changelog-2.0.sql
  migrations/master.xml
  pom.xml
  src/main/java/com/example/cbox/CBoxApplication.java
  src/main/java/com/example/cbox/annotation/TransactionalService.java
  src/main/java/com/example/cbox/annotation/ValidatedController.java
  src/main/java/com/example/cbox/config/MapperConfig.java
  src/main/java/com/example/cbox/config/RedisConfig.java
  src/main/java/com/example/cbox/controller/UserController.java
  src/main/java/com/example/cbox/dto/create/UserCreateEditDto.java
  src/main/java/com/example/cbox/dto/read/PageResponse.java
  src/main/java/com/example/cbox/dto/read/UserReadDto.java
  src/main/java/com/example/cbox/entity/AuditingEntity.java
  src/main/java/com/example/cbox/entity/User.java
  src/main/java/com/example/cbox/enumeration/UserStatus.java
  src/main/java/com/example/cbox/handler/ValidationExceptionHandler.java
  src/main/java/com/example/cbox/mapper/UserMapper.java
  src/main/java/com/example/cbox/repository/UserRepository.java
  src/main/java/com/example/cbox/service/UserService.java
  src/main/resources/application.yml
Labels: enhancement

#27 redis
  compose.yaml
  src/main/resources/application.yml
Labels: DB

#28 drawio
  docs/Admin.drawio
  docs/Document.drawio
  docs/Guest.drawio
  docs/User.drawio
Labels: documentation
